#!/bin/bash

# Just a little script to keep my wallpapers organized

cd pics
list=$(ls)
for file in $list; do
    mv "$file" "_""$file";
done

list=$(ls)
i=0
for file in $list; do
    suffix=${file##*.}
    if [[ $i -lt 10 ]]; then
        mv "$file" "pic_00"$i."$suffix";
    elif [[ $i -lt 100 ]]; then
        mv "$file" "pic_0"$i."$suffix";
    else
        mv "$file" "pic_"$i."$suffix";
    fi
    ((i++))
done
