#!/bin/bash

# Just a little script to keep my wallpapers organized

list=$(ls)
for file in $list; do
    if [[ $file == "pic-rename" || $file == "assets" || $file == "README.md" || $file == "LICENSE" || $file == "logos" || $file == "videos" || $file == "pic-wallogo" || $file == "wallogo" || $file == "ntbt" ]]; then
		continue
	fi
    mv "$file" "_""$file";
done

list=$(ls)
i=0
for file in $list; do
    if [[ $file == "pic-rename" || $file == "assets" || $file == "README.md" || $file == "LICENSE" || $file == "logos" || $file == "videos" || $file == "pic-wallogo" || $file == "wallogo" || $file == "ntbt" ]]; then
		continue
	fi
    suffix=${file##*.}
    if [[ $i -lt 10  ]]; then
        mv "$file" "pic_0"$i."$suffix";
    else
        mv "$file" "pic_"$i."$suffix";
    fi
    ((i++))
done
