#!/bin/bash

# Just a little script to keep my pictures organized

list=$(ls)
i=0
for file in $list; do
    if [[ $file == "rename_all" || $file == pics.png  || $file == README.md ]]; then
		continue
	fi
    suffix=${file##*.}
    if [[ $i -lt 10  ]]; then
        mv $file pic_0$i.$suffix;
    else
        mv $file pic_$i.$suffix;
    fi
    ((i++))
done
