#!/bin/bash

# Just a little script to keep my video-wallpapers organized

list=$(ls)
for file in $list; do
    if [[ $file == "rename-vid" ]]; then
		continue
	fi
    mv "$file" "_""$file";
done

list=$(ls)
i=0
for file in $list; do
    if [[ $file == "rename-vid" ]]; then
		continue
	fi
    suffix=${file##*.}
    if [[ $i -lt 10  ]]; then
        mv "$file" "vid_0"$i."$suffix";
    else
        mv "$file" "vid_"$i."$suffix";
    fi
    ((i++))
done
